[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "r8GQ9rM4c1MfZQFWU1Uj6CYoJzLxZbKu1fGzI-HoCK8"


[auth.google]
client_id = "376441768200-ga4equscrem6jraicrpke3or5j6tgk7q.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url ="https://accounts.google.com/.well-known/openid-configuration"